
package com.aquarius.DataAcquisition;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.6b21 
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AQAcquisitionService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://aq-demo-server/AQUARIUS/AqAcquisitionService.svc?wsdl")
public class AQAcquisitionService
    extends Service
{

    private final static URL AQACQUISITIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException AQACQUISITIONSERVICE_EXCEPTION;
    private final static QName AQACQUISITIONSERVICE_QNAME = new QName("http://tempuri.org/", "AQAcquisitionService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://aq-demo-server/AQUARIUS/AqAcquisitionService.svc?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AQACQUISITIONSERVICE_WSDL_LOCATION = url;
        AQACQUISITIONSERVICE_EXCEPTION = e;
    }

    public AQAcquisitionService() {
        super(__getWsdlLocation(), AQACQUISITIONSERVICE_QNAME);
    }

    public AQAcquisitionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AQACQUISITIONSERVICE_QNAME, features);
    }

    public AQAcquisitionService(URL wsdlLocation) {
        super(wsdlLocation, AQACQUISITIONSERVICE_QNAME);
    }

    public AQAcquisitionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AQACQUISITIONSERVICE_QNAME, features);
    }

    public AQAcquisitionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AQAcquisitionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IAQAcquisitionService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAQAcquisitionService")
    public IAQAcquisitionService getBasicHttpBindingIAQAcquisitionService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IAQAcquisitionService"), IAQAcquisitionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAQAcquisitionService
     */
    @WebEndpoint(name = "BasicHttpBinding_IAQAcquisitionService")
    public IAQAcquisitionService getBasicHttpBindingIAQAcquisitionService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IAQAcquisitionService"), IAQAcquisitionService.class, features);
    }

    /**
     * 
     * @return
     *     returns IAQAcquisitionService
     */
    @WebEndpoint(name = "WSHttpBinding_IAQAcquisitionService")
    public IAQAcquisitionService getWSHttpBindingIAQAcquisitionService() {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IAQAcquisitionService"), IAQAcquisitionService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IAQAcquisitionService
     */
    @WebEndpoint(name = "WSHttpBinding_IAQAcquisitionService")
    public IAQAcquisitionService getWSHttpBindingIAQAcquisitionService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IAQAcquisitionService"), IAQAcquisitionService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AQACQUISITIONSERVICE_EXCEPTION!= null) {
            throw AQACQUISITIONSERVICE_EXCEPTION;
        }
        return AQACQUISITIONSERVICE_WSDL_LOCATION;
    }

}
